/********************************************************************
  This script generated by gatekeeper permissions management tool
  date generated: {{dt}}

  To bring the users who currently exist in redshift to match the
  current gatekeeper configuration, run this script as a superuser
  against your redshift instance.

  This script should be reviewed before execution as it will remove
  users from the database who do not exist in the gatekeeper config.

  !!! --- THIS SCRIPT IS EXPERIMENTAL AND SHOULD BE REVIEWED --- !!!

*********************************************************************/

{% for iu in invalid_users%}
    {% for g in iu.groups%}
{% if loop.first %}
/**********************************************
  DROP GROUP ASSOCIATIONS FOR USER {{iu.name}}
***********************************************/
{%endif%}
ALTER GROUP {{g}} DROP USER {{iu.name}};
{% if loop.last %}

{%endif%}
    {%endfor%}
{%endfor%}


{% for iu in invalid_users%}
/**********************************************
 REMOVING USER {{iu.name}}
***********************************************/
DROP USER {{iu.name}};

{%endfor%}
