/*************************************************************************
  This file generated by the gatekeeper permissions management tool
  to reflect the configured object ownership in redshift for the {{user}} user.

    date generated: {{dt}}
    user name: {{user}}
**************************************************************************/
