/*************************************************************************
  This file generated by the gatekeeper permissions management tool
  and reflects the current state of object ownership in redshift
  for the {{user}} user.

    date generated: {{dt}}
    user name: {{user}}
**************************************************************************/

{% for key, db_objs in db_objects.items() %}
    {% for dbo in db_objs%}
    {% if loop.first %}

-- {{user}} is the owner of the following {{key.upper()}}S
    {% endif %}
{{dbo.create}};
    {% endfor %}
{% endfor %}
