/*************************************************************************
  This file generated by the gatekeeper permissions management tool
    date generated: {{dt}}
    user name: {{users.name}}
**************************************************************************/


-- create user password is stored somewhere in the parameter store
CREATE USER {{users.name}} WITH PASSWORD '{{users.password}}';

-- add the user {{users.name}} to its assigned groups through the role association.
{%for group in users.groups%}
ALTER GROUP {{group.name}} ADD USER {{users.name}};
{%endfor%}
