/*************************************************************************
  This file generated by the gatekeeper permissions management tool
    date generated: {{dt}}
    user name: {{user.name}}
**************************************************************************/


-- create user password is stored somewhere in the parameter store
CREATE USER {{user.name}} WITH PASSWORD '{{user.password}}';

-- add the user {{user.name}} to its assigned groups through the role association.
{%for group in user.groups%}
ALTER GROUP {{group.name}} ADD USER {{user.name}};
{%endfor%}
